id: A87A8E73F
base_file: fCDD9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:45:07.760231
  last_modified_at: 2022-05-31 06:45:07.760241
